graph LR
    1(["55560bdf<br/>ASSERTION"])
    2["7092d620<br/>#quot;knows#quot;"]
    3["9a771715<br/>#quot;Bob#quot;"]
    1 -->|pred| 2
    1 -->|obj| 3
    style 1 stroke-width:3.0px
    style 2 stroke-width:3.0px
    style 3 stroke-width:3.0px
    linkStyle 0 stroke-width:2.0px
    linkStyle 1 stroke-width:2.0px
